version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: back_gestao_loja_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: back_gestao_loja
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lojisto-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back_gestao_loja_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - lojisto-network

volumes:
  postgres_data:

networks:
  lojisto-network:
    driver: bridge